### variable precedence
# cli level
#task level
# role level
# play level




- name: Variables demo
  hosts: localhost
  connection: local
  vars:
    a: 100
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: a - {{ a }}

    - name: Variable from Inventory
      ansible.builtin.debug:
        msg: URL - {{ URL }}