### variable precedence
# cli level
#task level
# role level
# play level





- name: Variables demo1
  hosts: all
  tasks:
    - name: Variable from Inventory
      ansible.builtin.debug:
        msg: URL - {{ URL }}