- name: Loops Demo
  become: true
  hosts: localhost
  connection: local
  tasks:
    - name: Loop
      ansible.builtin.shell:
        msg: Hello - {{ item }}
      loop:
        - one
        - two

